### PR TITLE
[Color system] Sass variables to tokens

### LINKED ISSUE #74: [Sass API] Move Sass variables to polaris-tokens
# Context

For context on why we're doing this, see this issue: https://github.com/Shopify/polaris-react/issues/1982

**Why is this part of the Color system project?**

Good question. This work unlocks us (starting in version 5) to make changes to our Sass API without an impact on consumers. It will force consumers to stop relying on Polaris for Sass, and to use Tokens and their own internal Sass instead. Basically it paves the road for consumers to start using the Color system as CSS Custom properties, instead of using the `color` function (which will be removed) provided by Polaris Sass.

## Principles

- tokens should not be aliases to other tokens
- tokens should not do math for the consumer
- tokens should return pixel values and be transformed on the consumer
- tokens should convey **only** globally-useful data

⚠️ Names used in audit **do not** represent final names for tokens

### PR DESCRIPTION
**Pull request by danrosenthal**
Closes #74 

## New tokens added
https://github.com/Shopify/polaris-tokens/issues/74#issuecomment-526257016

### CODE REVIEW

**Comment by kaelig** [comment]
I fixed a bug in the html docs (the bug came from Theo). Another thing I need to look into is how we can keep CSS custom property names in camelCase rather than kebab-case.

**Comment by danrosenthal** [comment]
Thanks @kaelig!

Shadows don't look right on the docs. That could use a look

|shadows|
|-|
|Screen Shot 2019-08-30 at 2 15 32 PM|

**Comment by selenehinkley** [comment]
Would love to review these naming conventions in a pairing session if someone has time. I'm mainly curious what the new format for the `on` name is going to be, for example, `onSurface` or something like that.

**Comment by BPScott** [comment]
Not ran this, but code looks pretty reasonable to me.

>  Another thing I need to look into is how we can keep CSS custom property names in camelCase rather than kebab-case.

This sounds like a v3 thing. We're not going to be pushing consumers towards css-properties for immediate future, so I'd be happy to ship these as 2.x and we can look at camelCasing css properties as part of v3 along with other [breaking changes](https://github.com/Shopify/polaris-tokens/issues?q=is%3Aissue+is%3Aopen+label%3A%22breaking+change%22).

**Comment by BPScott** [comment]
Does this resolve #74?

**Comment by kaelig** [comment]
>This sounds like a v3 thing. We're not going to be pushing consumers towards css-properties for immediate future, so I'd be happy to ship these as 2.x and we can look at camelCasing css properties as part of v3 along with other breaking changes.

I shared my thoughts on this over here: https://github.com/Shopify/polaris-tokens/issues/75#issuecomment-526781758

I'm open to changing my mind, but with this project we already know where we want to be, and I don't think there is a case for a smooth migration path for consumers as there needs to be a clean cut anyways.

**Comment by BPScott** [comment]
Polaris-react can update from polaris-tokens v2 => v3 in a minor release, so there's no effect on that cadence.

It is really easy to not break people who are using polaris-tokens directly (which admittedly should be basically nobody as most people will be using them indirectly via polaris-react's utility functions) so it feels like it is worth doing from a good hygiene perspective. In the past you were reticent to introduce a change in v2.x to simpliy the contents of colors.yml arguing it was technically a breaking change, I'd say the impact of changing the casing of custom-properties is higher than that of changing the color.yml aliasing.

Proposed plan:
 
- Ship this PR and cut a polaris-tokens 2.7 release
- Update polaris-react to use polaris-tokens 2.7 and ship in a minor version
- At the point that we need camel-cased custom properties (which won't be for a while till the new color naming conventions kick in) create a new PR that changes casing of custom-properties and updates colors.yml including removing aliasing, release this as polaris-tokens 3.0
- Update polaris-react to use polaris-tokens 3.0 and release as a minor version of polaris-react

**Comment by kaelig** [comment]
The upgrade path proposed here as I understand it from a consumer's perspective:
Sass helpers -> Sass variables in kebab-case (v2.7) -> Sass variables in camelCase (v3.0) -> brand system custom properties (v4.0)

My proposal:
Sass helpers -> ~~Sass variables in kebab-case (v2.7)~~ -> Sass variables in camelCase (v3.0) -> brand system custom properties (v4.0)

If we made a mistake, we can go back and ship a 2.7 with the new Sass variables in kebab-case.

I also suggest we keep shipping v3.0.0 **beta.x** versions to leave us a lot of room for change and rapid iteration during this transition.

**Comment by tmlayton** [comment]
Unless I’m missing something with how Theo works, the kebab-case and camelCase issue doesn’t have to be a breaking change. Just add the camelCase values as duplicates once it is sorted, then the breaking change only comes when we remove the deprecated values. It’s a bit between the lines, but covered in this [implementation plan](https://docs.google.com/document/d/1rbndsYKoKfMpN8C3JTAEjR7iTgylQjHVsoIt1407nWE/edit#heading=h.dyb9muo3n6m). The general idea is to only add new values even if that means duplication. The same thinking would apply to renaming values, duplicate it with the new name. Then when we are all sorted, remove what we don’t want and release v3.

**Comment by tmlayton** [comment]
There also appears to be a concept of `aliases`. Is that something we can use?

**Comment by tmlayton** [comment]
@danrosenthal and I just chatted and we are good moving forward with kebab-case. We’ll update the yml accordingly.

**Pull request closed without merging**
