### PR TITLE
Move onSurface.onSurfaceBackground to surface.surfaceSearchField

### PR DESCRIPTION
**Pull request by AdamVig**
**Commits**
- Move onSurface.onSurfaceBackground to surface.surfaceSearchField  
  This fixes the non-unique `figmaName` of this variant, too, which
  unblocks #178.

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
This makes sense to me but will need to be documented in [CHANGELOG.md](https://github.com/Shopify/polaris-tokens/blob/main/CHANGELOG.md) as it will likely break consumers using the current value.

**Review by kyledurand — APPROVED** [review]
The name change makes sense just be sure to add an entry to the changelog like Alex mentioned. Just under `<!-- ## [Unreleased] -->` at the top of the file

**Review by kyledurand — APPROVED** [review]
👍

**Comment by AdamVig** [comment]
@kaelig I found the following references of `--p-on-surface-background` and `onSurfaceBackground`:
- `polaris-styleguide`
  - Three definitions in `web/styleguide-demo/Demo/test/Demo.test.tsx`, but it looks like they might be automatically generated
- `polaris-react`
  - Three uses in `src/components/TopBar/components/SearchField/SearchField.scss`.
  - Documentation in `documentation/Color system.md`, but it looks like it is automatically updated when the tokens change.
  - Defined in `src/components/README.md`, does not seem to be automatically updated when tokens change.
- No references that I could find in Vault.

I don't think I have time to cut a release of `polaris-tokens` and update those other repositories in the near future, but if that work is absolutely necessary in order to merge this, I can do it in a few weeks.

**Comment by alex-page** [comment]
I can do the release this should be good to merge.

**Comment by AdamVig** [comment]
Thanks, @alex-page!

**Pull request merged**
