### PR TITLE
remove package_cloud from deploy

### PR DESCRIPTION
**Pull request by nwtn**
rubygems deploy isn’t happening. let’s see if removing this helps.

### CODE REVIEW

**Comment by nwtn** [comment]
here’s the deploy: https://shipit.shopify.io/shopify/polaris-tokens/production/deploys/554069

publishing to package_cloud seemed to work; my thinking is that it’s overriding the deploy to rubygems. `npm publish` worked: https://www.npmjs.com/package/@shopify/polaris-tokens.

**Comment by kaelig** [comment]
We still need a gem publishing step somewhere, no? Worth pinging Ismail if you need help with this.

**Comment by nwtn** [comment]
> We still need a gem publishing step somewhere, no?

my understanding is that https://github.com/Shopify/polaris-tokens/blob/master/shipit.rubygems.yml will trigger rubygems publishing. @ismail-syed thoughts?

**Comment by ismail-syed** [comment]
I'm not to familiar with publishing ruby gems. I would ping the dev-accel oncall for this.

**Comment by nwtn** [comment]
screen shot 2018-04-18 at 12 42 07 pm

once this goes through and publishing to rubygems is working, i'll open the issue in dev-accel to 🔥 the package_cloud version

cc @wvanbergen

**Comment by kaelig** [comment]
Since we override the deploy step I'm confused as to why this may work at all, but let's merge and try!

**Comment by nwtn** [comment]
no dice. i will try once more by adding `bundle exec rake release` to the manual deploy override (and delete the `shipit.rubygems.yml` file). 

see https://github.com/Shopify/shipit-engine/blob/9916492bb59476188e0babbda02c01b8a76c3255/app/models/shipit/deploy_spec/rubygems_discovery.rb#L32

**Pull request merged**
