### PR TITLE
Start using Google Spreadsheets to manage design tokens

### PR DESCRIPTION
**Pull request by kaelig**
I suggest that we use Google Spreadsheets to manage all design tokens, starting with colors.

### Source of truth in Google Spreadsheets

- [Design tokens spreadsheet](https://docs.google.com/spreadsheets/d/1HzVgcxnnOCeB2zI46gcSd5fPFUJ2R03CSldx_SKQQwA/edit#gid=0)
- [Web format](https://docs.google.com/spreadsheets/d/e/2PACX-1vSSomjdTD8hyshH2JRRl1uDZkZKI5BpQu16KqA35bzqNaiX-pATDw1vLRP3XqxGnxDlZ0lIL-wfmc9f/pubhtml) (read only)
- [JSON](https://spreadsheets.google.com/feeds/list/1HzVgcxnnOCeB2zI46gcSd5fPFUJ2R03CSldx_SKQQwA/1/public/values?alt=json) (used to import tokens into this repository)

### Why?

- In my experience, managing a token library with YAML is tedious, with a high barrier of entry for designers
- As seen recently with @alex-page's experience for [changing the blue color](#63), not everyone at Shopify has access to Invision DSM (previously used to manage color tokens)
- Everyone at Shopify has access to Google Spreadsheets, and we can restrict who can edit certain fields (rights management), see a change history, suggest changes, comment on cells…
- DSM doesn't surface any fields other than key / value pairs (name / color value), so as a workaround for storing color metadata, we have a [`/data/`](https://github.com/Shopify/polaris-tokens/tree/ac98aba43f6d47a774a96f1cdeed984bbdab34dc/data) folder, whereas Google Spreadsheets allows us to store as much metadata as needed

### Alternative

The alternative is to drop DSM and rely on a YAML-only solution to manage colors, and reassess later this year if we want to manage colors using any sort of CMS.

---

### :tophat:

This should work:

```
dev cd polaris-tokens
yarn
git checkout spreadsheets
yarn get-tokens-from-google-spreadsheets
yarn dist
```

---

@alex-page considering your work on colors with @AndrewMusgrave, how do you feel about this approach? Could it integrate at all with how color systems will evolve?

@danrosenthal pinging you related to https://github.com/Shopify/polaris-react/issues/1593, in case you're interested!

@nwtn this PR removes the `/data/` folder, as metadata can be handled in the spreadsheet.

@BPScott feedback/questions on the approach are welcome, as well as comments on the code of `get-tokens-from-google-spreadsheets.js`

---

~PS: ignore changes to the `/dist/` folder – they will go away as soon as #64 is merged~ rebased!

### CODE REVIEW

**Comment by nwtn** [comment]
> @nwtn this PR removes the /data/ folder, as metadata can be handled in the spreadsheet.

i’m good with this :+1:

**Comment by BPScott** [comment]
I like the idea of moving away from Invision, however I'm not convinced that a spreadsheet offers much improvement over a json/yaml file that lives within this repository. It still results in there being a two step process to populate data rather than having everything needed only within this repository.

Looking at the contents of your current spreadsheet it looks like all the only fields that need to be user-provided about are name, value and description. Everything else is can be derived from those three fields.

If we push the dynamic generation of friendlyName and filter out to whatever file needs those we can have a colors.yml whose items that look like:

```yml
  - name: color-purple-text
    value: ''#50495a''
    meta:
      category: text-color
```

Which feels pretty straightforward to manage by hand - no more complex than the yaml files we ask people to maintain for icons

**Comment by kaelig** [comment]
At the moment I agree it's totally manageable by hand. It's probably me overcorrecting from past experience.

---

#### For context

The previous system I worked on had theming and component-specific design tokens added to that, which led to… https://www.lightningdesignsystem.com/design-tokens/ (>250 tokens, not counting the overrides).

This is where tokens are managed at Salesforce: https://github.com/salesforce-ux/design-system/tree/master/design-tokens

I remember it being complex to manage, version, and update.

**Comment by BPScott** [comment]
Your fear of being bitten by the problems you found elsewhere are legit, but I don't think they'll affect us, mostly due to how static our tokens are.

Component-specific tokens are out of scope for us as far as I can tell, which means we only have to deal with a smallish data set - we're never going to grow to have that many tokens and the rate at which we change our icons is pretty glacial.

[Here's the diff from v2, which was released in October 2018](https://github.com/Shopify/polaris-tokens/compare/v2.0.0...master). In the past 9 months we have: changed 2 colors, added duration tokens, added spacing-tight and updated our 2 font tokens to strip out quotes. That's a really tiny list for that amount of time.

Because we don't have the constant churn of component tokens always being added I don't think we need to invest in systems that allow for rapid editing of tokens by all, just because it doesn't happen that often.

---

One other counter reason: Currently would be possible for the spreadsheet and the contents of this repo to get out of sync - designers can edit the spreadsheet but they'd still need to come and touch this repository afterwards. By making this repo the source of truth it means people only have a single place to go.

**Comment by kaelig** [comment]
Thanks @BPScott – these are very good points. I'm curious to hear what @alex-page may have to say about this approach. In parallel I'll open a PR that removes the reliance on DSM for updating colors.

**Comment by danrosenthal** [comment]
This approach makes perfect sense to me. :shipit:

**Comment by kaelig** [comment]
Thank you all for looking into this.

I'm closing the PR for now, because as @bpscott pointed out, it adds an additional step, and we can still rely on YAML files hosted on GitHub at our scale.

If we end up revamping the color system or have way more tokens, I suggest we think about Google Spreadsheets again.

**Pull request closed without merging**
